from PyQt5 import QtCore, QtGui, QtWidgets
from language import LanguageDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(500, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 200, 8000, 8000))
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRecent = QtWidgets.QMenu(self.centralwidget)
        self.menuRecent.setObjectName("Recent")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_Database = QtWidgets.QAction(MainWindow)
        self.actionNew_Database.setEnabled(True)
        self.actionNew_Database.setAutoRepeat(True)
        self.actionNew_Database.setVisible(True)
        self.actionNew_Database.setObjectName("actionNew_Database")
        self.actionOpen_Database = QtWidgets.QAction(MainWindow)
        self.actionOpen_Database.setObjectName("actionOpen_Database")
        self.actionSave_Database_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Database_As.setObjectName("actionSave_Database_As")
        self.actionExit_Program = QtWidgets.QAction(MainWindow)
        self.actionExit_Program.setObjectName("actionExit_Program")
        self.actionFullscreen = QtWidgets.QAction(MainWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionFontSizePlus = QtWidgets.QAction(MainWindow)
        self.actionFontSizePlus.setObjectName("actionFontSizePlus")
        self.actionFontSizeMinus = QtWidgets.QAction(MainWindow)
        self.actionFontSizeMinus.setObjectName("actionFontSizeMinus")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew_Database)
        self.menuFile.addAction(self.actionOpen_Database)
        self.menuFile.addAction(self.actionSave_Database_As)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addAction(self.actionExit_Program)
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.actionLanguage)
        self.menuView.addAction(self.actionFontSizePlus)
        self.menuView.addAction(self.actionFontSizeMinus)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.centralwidget.resizeEvent = lambda event: self.adjustGeometry(self.centralwidget.width(), self.centralwidget.height())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"{LanguageDialog().txt_title()}"))
        self.label.setText(_translate("MainWindow", f"{LanguageDialog().txt_title()}"))
        self.menuFile.setTitle(_translate("MainWindow", f"{LanguageDialog().txt_file()}"))
        self.menuView.setTitle(_translate("MainWindow", f"{LanguageDialog().txt_view()}"))
        self.menuHelp.setTitle(_translate("MainWindow", f"{LanguageDialog().txt_help()}"))
        self.menuRecent.setTitle(_translate("MainWindow", f"{LanguageDialog().txt_recent()}"))
        self.actionNew_Database.setText(_translate("MainWindow", f"{LanguageDialog().txt_newdb()}"))
        self.actionNew_Database.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen_Database.setText(_translate("MainWindow", f"{LanguageDialog().txt_opendb()}"))
        self.actionOpen_Database.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Database_As.setText(_translate("MainWindow", f"{LanguageDialog().txt_savedbas()}"))
        self.actionSave_Database_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit_Program.setText(_translate("MainWindow", f"{LanguageDialog().txt_exit()}"))
        self.actionFullscreen.setText(_translate("MainWindow", f"{LanguageDialog().txt_fullscreen()}"))
        self.actionFullscreen.setShortcut(_translate("MainWindow", "F11"))
        self.actionLanguage.setText(_translate("MainWindow", f"{LanguageDialog().txt_language()}"))
        self.actionFontSizePlus.setText(_translate("MainWindow", f"{LanguageDialog().txt_fontsize()}"+" +"))
        self.actionFontSizePlus.setShortcut(_translate("MainWindow", "F9"))
        self.actionFontSizeMinus.setText(_translate("MainWindow", f"{LanguageDialog().txt_fontsize()}"+" -"))
        self.actionFontSizeMinus.setShortcut(_translate("MainWindow", "F8"))
        self.actionAbout.setText(_translate("MainWindow", f"{LanguageDialog().txt_about()}"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))

    def adjustGeometry(self, width, height):
        font_size = min(width // 20, height // 4)

        font = QtGui.QFont()
        font.setPointSize(font_size)
        self.label.setFont(font)

        label_width = self.label.width()
        label_height = self.label.height()
        label_x = (width - label_width) // 2
        label_y = (height - label_height) // 2
        self.label.setGeometry(label_x, label_y, label_width, label_height)
